name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create Release APK
      run: ./gradlew assembleRelease
    - name: Sign APK with keystore
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.BASE_64_KEY }}
        alias: keyAlias
        keyStorePassword: password
        keyPassword: password
    - uses: actions/upload-artifact@master
      with:
        name: release.apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
    - uses: actions/upload-artifact@master
      with:
        name: mapping.txt
        path: app/build/outputs/mapping/release/mapping.txt
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{steps.sign_app.outputs.signedReleaseFile}}/release.apk